Repository SciCompMod/memilio, pull requests merged in 2023-11, with the labels that each got.

#816 809 error in comopilation of apple clang 15.0.0
  cpp/cmake/BuildBoost.cmake
Labels: class::bug, loc::infrastructure

#825 815 mock distributions for test consistencyStochasticMobility
  cpp/tests/test_graph_simulation.cpp
Labels: loc::continuous integration, class::improvement

#837 836 fix GitHub links
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/doc.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/pull_request_template.md
  README.md
  cpp/benchmarks/flow_simulation_ode_secirvvs.h
  cpp/benchmarks/flow_simulation_ode_seir.cpp
  cpp/models/ode_secir/README.md
  cpp/models/ode_secirvvs/README.md
  cpp/models/ode_seir/README.md
  cpp/models/ode_sir/README.md
  docs/README.md
  docs/index.html
  pycode/memilio-epidata/README.rst
  pycode/memilio-epidata/memilio/epidata/README.rst
  pycode/memilio-epidata/setup.py
  pycode/memilio-generation/setup.py
  pycode/memilio-plot/README.md
  pycode/memilio-plot/setup.py
  pycode/memilio-simulation/setup.py
  pycode/memilio-surrogatemodel/README.md
  pycode/memilio-surrogatemodel/memilio/surrogatemodel/ode_secir_simple/README.md
  pycode/memilio-surrogatemodel/setup.py
Labels: class::documentation

#828 756 ABM benchmark
  cpp/benchmarks/CMakeLists.txt
  cpp/benchmarks/abm.cpp
  cpp/memilio/utils/random_number_generator.h
  cpp/memilio/utils/stl_util.h
  cpp/tests/test_stl_util.cpp
Labels: model::abm, class::performance
