Repository SciCompMod/memilio, pull requests merged in 2024-11, with the labels that each got.

#1140 1138 plot functions for ast in generation package
  pycode/memilio-generation/memilio/generation/__init__.py
  pycode/memilio-generation/memilio/generation/ast.py
  pycode/memilio-generation/memilio/generation/graph_visualization.py
  pycode/memilio-generation/memilio/generation/scanner.py
  pycode/memilio-generation/memilio/generation/utility.py
  pycode/memilio-generation/memilio/generation_test/test_oseir_generation.py
  pycode/memilio-generation/memilio/tools/example_oseir.py
  pycode/memilio-generation/setup.py
Labels: class::feature

#1072 652 Add serialization to ABM
  cpp/CMakeLists.txt
  cpp/memilio/CMakeLists.txt
  cpp/memilio/io/README.md
  cpp/memilio/io/binary_serializer.h
  cpp/memilio/io/default_serialize.cpp
  cpp/memilio/io/default_serialize.h
  cpp/memilio/io/io.h
  cpp/memilio/math/interpolation.h
  cpp/memilio/math/time_series_functor.cpp
  cpp/memilio/math/time_series_functor.h
  cpp/memilio/utils/random_number_generator.h
  cpp/memilio/utils/time_series.h
  cpp/models/abm/infection.h
  cpp/models/abm/location.h
  cpp/models/abm/mask.h
  cpp/models/abm/model.h
  cpp/models/abm/parameters.h
  cpp/models/abm/person.h
  cpp/models/abm/test_type.h
  cpp/models/abm/testing_strategy.h
  cpp/models/abm/time.h
  cpp/models/abm/trip_list.h
  cpp/models/abm/vaccine.h
  cpp/simulations/abm.cpp
  cpp/simulations/abm_braunschweig.cpp
  cpp/tests/CMakeLists.txt
  cpp/tests/matchers.cpp
  cpp/tests/matchers.h
  cpp/tests/random_number_test.h
  cpp/tests/test_abm_infection.cpp
  cpp/tests/test_abm_model.cpp
  cpp/tests/test_abm_serialization.cpp
  cpp/tests/test_flows.cpp
  cpp/tests/test_io_cli.cpp
  cpp/tests/test_json_serializer.cpp
  cpp/tests/test_math_time_series_functor.cpp
  cpp/tests/test_odesecir.cpp
  docs/Doxyfile
  pycode/memilio-simulation/memilio/simulation/bindings/pickle_serializer.h
Labels: class::feature, loc::backend, model::abm

#1146 1021 Error when compiling on Mac with new boost
  cpp/CMakeLists.txt
  cpp/tests/test_abm_serialization.cpp
  cpp/thirdparty/CMakeLists.txt
Labels: loc::backend
