Repository SciCompMod/memilio, pull requests merged in 2024-08, with the labels that each got.

#1076 Increase accuracy of code coverage
  cpp/CMakeLists.txt
Labels: loc::continuous integration, class::improvement

#1094 1092 add warning for end_date later than 2024-07-21 in divi data
  pycode/memilio-epidata/memilio/epidata/getDIVIData.py
Labels: loc::data handling, class::improvement

#1106 1105 redesign bindings structure to improve typing
  pycode/memilio-simulation/CMakeLists.txt
  pycode/memilio-simulation/README.md
  pycode/memilio-simulation/memilio/simulation/__init__.py
  pycode/memilio-simulation/memilio/simulation/abm.py
  pycode/memilio-simulation/memilio/simulation/bindings/compartments/compartmentalmodel.h
  pycode/memilio-simulation/memilio/simulation/bindings/compartments/flow_simulation.h
  pycode/memilio-simulation/memilio/simulation/bindings/compartments/simulation.h
  pycode/memilio-simulation/memilio/simulation/bindings/epidemiology/age_group.h
  pycode/memilio-simulation/memilio/simulation/bindings/epidemiology/contact_matrix.h
  pycode/memilio-simulation/memilio/simulation/bindings/epidemiology/damping.h
  pycode/memilio-simulation/memilio/simulation/bindings/epidemiology/damping_sampling.cpp
  pycode/memilio-simulation/memilio/simulation/bindings/epidemiology/damping_sampling.h
  pycode/memilio-simulation/memilio/simulation/bindings/epidemiology/dynamic_npis.h
  pycode/memilio-simulation/memilio/simulation/bindings/epidemiology/populations.h
  pycode/memilio-simulation/memilio/simulation/bindings/epidemiology/simulation_day.h
  pycode/memilio-simulation/memilio/simulation/bindings/epidemiology/uncertain_matrix.cpp
  pycode/memilio-simulation/memilio/simulation/bindings/epidemiology/uncertain_matrix.h
  pycode/memilio-simulation/memilio/simulation/bindings/io/mobility_io.h
  pycode/memilio-simulation/memilio/simulation/bindings/io/result_io.h
  pycode/memilio-simulation/memilio/simulation/bindings/mobility/graph_simulation.h
  pycode/memilio-simulation/memilio/simulation/bindings/mobility/metapopulation_mobility_instant.cpp
  pycode/memilio-simulation/memilio/simulation/bindings/mobility/metapopulation_mobility_instant.h
  pycode/memilio-simulation/memilio/simulation/bindings/models/abm.cpp
  pycode/memilio-simulation/memilio/simulation/bindings/models/osecir.cpp
  pycode/memilio-simulation/memilio/simulation/bindings/models/osecirvvs.cpp
  pycode/memilio-simulation/memilio/simulation/bindings/models/oseir.cpp
  pycode/memilio-simulation/memilio/simulation/bindings/models/osir.cpp
  pycode/memilio-simulation/memilio/simulation/bindings/pickle_serializer.h
  pycode/memilio-simulation/memilio/simulation/bindings/pybind_util.h
  pycode/memilio-simulation/memilio/simulation/bindings/simulation.cpp
  pycode/memilio-simulation/memilio/simulation/bindings/utils/custom_index_array.h
  pycode/memilio-simulation/memilio/simulation/bindings/utils/date.cpp
  pycode/memilio-simulation/memilio/simulation/bindings/utils/date.h
  pycode/memilio-simulation/memilio/simulation/bindings/utils/index.h
  pycode/memilio-simulation/memilio/simulation/bindings/utils/logging.cpp
  pycode/memilio-simulation/memilio/simulation/bindings/utils/logging.h
  pycode/memilio-simulation/memilio/simulation/bindings/utils/parameter_distributions.cpp
  pycode/memilio-simulation/memilio/simulation/bindings/utils/parameter_distributions.h
  pycode/memilio-simulation/memilio/simulation/bindings/utils/parameter_set.h
  pycode/memilio-simulation/memilio/simulation/bindings/utils/time_series.cpp
  pycode/memilio-simulation/memilio/simulation/bindings/utils/time_series.h
  pycode/memilio-simulation/memilio/simulation/bindings/utils/uncertain_value.cpp
  pycode/memilio-simulation/memilio/simulation/bindings/utils/uncertain_value.h
  pycode/memilio-simulation/memilio/simulation/osecir.py
  pycode/memilio-simulation/memilio/simulation/osecirvvs.py
  pycode/memilio-simulation/memilio/simulation/oseir.py
  pycode/memilio-simulation/memilio/simulation/osir.py
  pycode/memilio-simulation/requirements-dev.txt
  pycode/memilio-simulation/setup.py
  pycode/memilio-simulation/tools/generate_stubs.py
  pyproject.toml
Labels: loc::python interface, class::improvement

#1114 1113 missing includes in python bindings
  pycode/memilio-simulation/CMakeLists.txt
Labels: class::bug

#1103 1098 bind different integrators for python
  pycode/memilio-simulation/memilio/simulation/bindings/compartments/flow_simulation.h
  pycode/memilio-simulation/memilio/simulation/bindings/compartments/simulation.h
  pycode/memilio-simulation/memilio/simulation/bindings/math/integrator.h
  pycode/memilio-simulation/memilio/simulation/bindings/models/osecir.cpp
  pycode/memilio-simulation/memilio/simulation/bindings/models/osecirvvs.cpp
  pycode/memilio-simulation/memilio/simulation/bindings/models/oseir.cpp
  pycode/memilio-simulation/memilio/simulation/bindings/models/osir.cpp
  pycode/memilio-simulation/memilio/simulation/bindings/simulation.cpp
  pycode/memilio-simulation/memilio/simulation_test/test_integrators.py
Labels: loc::python interface, class::improvement
