Repository SciCompMod/memilio, pull requests merged in 2024-07, with the labels that each got.

#1055 914 make the lct secir model a derived class of flowmodel
  cpp/examples/lct_secir.cpp
  cpp/memilio/compartments/compartmentalmodel.h
  cpp/memilio/epidemiology/lct_infection_state.h
  cpp/models/lct_secir/CMakeLists.txt
  cpp/models/lct_secir/model.h
  cpp/models/lct_secir/parameters_io.h
  cpp/models/lct_secir/simulation.h
  cpp/tests/test_lct_parameters_io.cpp
  cpp/tests/test_lct_secir.cpp
Labels: model::lct

#1060 Fix a "use after free" warning with gcc 12.3.0 and above
  cpp/memilio/epidemiology/damping.h
Labels: class::bug, loc::backend

#1063 workaround for github action checkout@v3
  .github/workflows/main.yml
Labels: class::bug, prio::critical, loc::continuous integration

#1066 Remove call to print_table from TestSeir.FlowSimulation
  cpp/tests/test_odeseir.cpp
Labels: class::bug, loc::backend

#1062 1061 change return type of check_constraints function in the populations class to bool
  cpp/memilio/compartments/compartmentalmodel.h
  cpp/memilio/epidemiology/populations.h
  cpp/models/lct_secir/initializer_flows.h
  cpp/tests/test_populations.cpp
Labels: model::ode
