Repository SciCompMod/memilio, pull requests merged in 2025-04, with the labels that each got.

#1236 Remove debug output from SDE seirvv model
  cpp/models/sde_seirvv/model.h
Labels: loc::backend, model::sde

#1240 Bump minimum cmake versions in memilio-simulation and -generation
  pycode/memilio-generation/CMakeLists.txt
  pycode/memilio-simulation/CMakeLists.txt
Labels: loc::python interface

#1254 1228-update-coding-guidelines
  docs/source/development.rst
  docs/source/models/sde_sirs.rst
Labels: class::bug

#1153 1019 Adjust memilio-generation for flow models and automatic differentiation
  pycode/memilio-generation/README.md
  pycode/memilio-generation/memilio/generation/__init__.py
  pycode/memilio-generation/memilio/generation/ast.py
  pycode/memilio-generation/memilio/generation/default_generation_dict.py
  pycode/memilio-generation/memilio/generation/generator.py
  pycode/memilio-generation/memilio/generation/graph_visualization.py
  pycode/memilio-generation/memilio/generation/intermediate_representation.py
  pycode/memilio-generation/memilio/generation/scanner.py
  pycode/memilio-generation/memilio/generation/scanner_config.py
  pycode/memilio-generation/memilio/generation/template/template_cpp.txt
  pycode/memilio-generation/memilio/generation/template/template_string.py
  pycode/memilio-generation/memilio/generation/utility.py
  pycode/memilio-generation/memilio/generation_test/test_data/test_oseir.cpp.txt
  pycode/memilio-generation/memilio/generation_test/test_oseir_generation.py
  pycode/memilio-generation/memilio/tools/README.md
  pycode/memilio-generation/memilio/tools/config.json
  pycode/memilio-generation/memilio/tools/config.json.txt
  pycode/memilio-generation/memilio/tools/example_oseir.py
Labels: class::feature, status::in progress, class::improvement
